### ISSUE TITLE
Landing page HI-FI

### ISSUE THREAD

**Issue by mbuguaellen** [zuri-training/proj_fetch_meta_data_Team_84#12]
The landing page 
 https://www.figma.com/file/JQtpoNpLc7SeBEHpormEqh/Team84_fetch_metadata-collaboration?node-id=486%3A1347

**Comment by Ade-Bani** [comment]
Page complete.

**Comment by Daeveed1** [comment]
Web View -  https://www.figma.com/file/JQtpoNpLc7SeBEHpormEqh/Team84_fetch_metadata-collaboration?node-id=486%3A1347

Mobile view - https://www.figma.com/file/JQtpoNpLc7SeBEHpormEqh/Team84_fetch_metadata-collaboration?node-id=1701%3A2296

**Comment by Daeveed1** [comment]
Mobile view https://www.figma.com/file/JQtpoNpLc7SeBEHpormEqh/Team84_fetch_metadata-collaboration?node-id=1701%3A2296
