### ISSUE TITLE
FAQS HI-FI

### ISSUE THREAD

**Issue by mbuguaellen** [zuri-training/proj_fetch_meta_data_Team_84#3]

**Comment by mbuguaellen** [comment]
https://www.figma.com/file/JQtpoNpLc7SeBEHpormEqh/Team84_fetch_metadata-collaboration?node-id=1325%3A1701

**Comment by Wuraola-Omotoyosi** [comment]
I worked on the HiFi of the FAQ Pages (Both when the page is interactive or not)

Below is the link.
https://www.figma.com/file/JQtpoNpLc7SeBEHpormEqh/Team84_fetch_metadata-collaboration?node-id=1325%3A1701

**Comment by mbuguaellen** [comment]
Well done
