### ISSUE TITLE
Styles Guide

### ISSUE THREAD

**Issue by mbuguaellen** [zuri-training/proj_fetch_meta_data_Team_84#47]
page is complete

**Comment by OreoluwaDahunsi** [comment]
https://www.figma.com/file/JQtpoNpLc7SeBEHpormEqh/Team84_fetch_metadata-collaboration?node-id=2%3A2

**Comment by Enojay** [comment]
https://www.figma.com/file/JQtpoNpLc7SeBEHpormEqh/Team84_fetch_metadata-collaboration?node-id=2%3A2
