### ISSUE TITLE
User flow

### ISSUE THREAD

**Issue by mbuguaellen** [zuri-training/proj_fetch_meta_data_Team_84#49]

**Comment by olawoyintosin** [comment]
What is left to do on the user flow...I thought it is complete?

**Comment by olawoyintosin** [comment]
https://www.figma.com/file/JQtpoNpLc7SeBEHpormEqh/Team84_fetch_metadata-collaboration?node-id=1636%3A1852

**Comment by olawoyintosin** [comment]
https://www.figma.com/file/0YyH4VImuyfpTcKR0z6CkF/Userflow%2C-user-story%2C-empathy-map%2C-impact-effort-matrix?node-id=0%3A1

**Comment by olawoyintosin** [comment]
https://www.figma.com/file/0YyH4VImuyfpTcKR0z6CkF/Userflow%2C-user-story%2C-empathy-map%2C-impact-effort-matrix?node-id=0%3A1
